### ISSUE TITLE
Cannot read properties of undefined (reading '_bn')

### ISSUE THREAD

**Issue by yrgenkuci** [MicroHD/Candy-Machine-V2-Minter#1]
Hi, been trying to run your repo but I am getting Cannot read properties of undefined (reading '_bn') and a white screen when running this on localhost. Any solution around this?

**Comment by MicroHD** [comment]
Rename the `.env.template` file to `.env` inside the file make sure to input with your candy machine details. You get your candy machine id after you upload your NFT collection with Metaplex.
