### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by kiankyars** [MicroHD/Candy-Machine-V2-Minter#2]
We are looking for a way to deploy our nft minting website without too much trouble, (have only done a 2 hour react crash course), has anyone used this repository for minting an NFT, and if so, was everything good, because the main thing I'm worried about is something going wrong during mint and being unable to fix it.

**Comment by MicroHD** [comment]
> We are looking for a way to deploy our nft minting website without too much trouble, (have only done a 2 hour react crash course), has anyone used this repository for minting an NFT, and if so, was everything good, because the main thing I'm worried about is something going wrong during mint and being unable to fix it.

I can point you all in the right direction, this is pretty straightforward first thing is to go here the [metaplex  docs](https://docs.metaplex.com/candy-machine-v2/getting-started) create a candy machine. The next step after your NFT collection is on a candy machine is to clone this script follow the directions edit the .env.template file with your candy machine info, rename it.

 Edit the components and how you want. That's all you need to do with this repo, you can edit the minter how you want for your own NFT project. Hopefully that helps, if you have any more questions, feel free to ask I'll try to help the best I can.

**Comment by kiankyars** [comment]
Yea that makes sense, also just wondering what you are referring to when you say "this script" and a general question: are there any known issues with a sudden high traffic on the minting process, and would this issue be on the domain side or the hosting side (I plan on using GitHub) thanks!

**Comment by MicroHD** [comment]
> Yea that makes sense, also just wondering what you are referring to when you say "this script" and a general question: are there any known issues with a sudden high traffic on the minting process, and would this issue be on the domain side or the hosting side (I plan on using GitHub) thanks!

This repo ("This script") is only to provide a frontend UI website for users to come mint your NFT collection. You still need to upload your NFT collection with Metaplex candy machine to take advantage of this repo. There's no known issues that I am aware of with any sudden high traffic spikes. This issue would be on your web hosting side, not domain.
